// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4CkNVnw1BzKtZ1Ea0Jl9_k8-bjFwW-Eg',
    appId: '1:38448933378:web:a51f512f9def25761b151b',
    messagingSenderId: '38448933378',
    projectId: 'test-7fefc',
    authDomain: 'test-7fefc.firebaseapp.com',
    storageBucket: 'test-7fefc.appspot.com',
    measurementId: 'G-CVX68H7Y7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpNBMAC7mDagLgkL6eqJWLrAHUxjcZXsw',
    appId: '1:38448933378:android:ed96868c93db49de1b151b',
    messagingSenderId: '38448933378',
    projectId: 'test-7fefc',
    storageBucket: 'test-7fefc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk7oIHwXzB-0goVQqMvx2WDPA3Qa9Uods',
    appId: '1:38448933378:ios:d5aa70a50d40ac291b151b',
    messagingSenderId: '38448933378',
    projectId: 'test-7fefc',
    storageBucket: 'test-7fefc.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk7oIHwXzB-0goVQqMvx2WDPA3Qa9Uods',
    appId: '1:38448933378:ios:d5aa70a50d40ac291b151b',
    messagingSenderId: '38448933378',
    projectId: 'test-7fefc',
    storageBucket: 'test-7fefc.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4CkNVnw1BzKtZ1Ea0Jl9_k8-bjFwW-Eg',
    appId: '1:38448933378:web:13dd07126d25cb4f1b151b',
    messagingSenderId: '38448933378',
    projectId: 'test-7fefc',
    authDomain: 'test-7fefc.firebaseapp.com',
    storageBucket: 'test-7fefc.appspot.com',
    measurementId: 'G-BW07B6FPWC',
  );
}
